import { test, expect } from '@playwright/test'

test('NivoraX All Pages screen loads', async ({ page }) => {
  await page.goto('/wp-admin/admin.php?page=nivorax')

  // Confirms the plugin booted and the admin menu was registered
  await expect(page.locator('.wrap h1')).toContainText('All Pages')
})

test('NivoraX editor loads for a page', async ({ page }) => {
  await page.goto('/wp-admin/admin.php?page=nivorax')

  // The table lists pages — click the first title link.
  // The link is generated by EditorScreen::url() and carries a valid server-side nonce.
  const firstPageLink = page.locator('table.wp-list-table tbody tr:first-child td:first-child a')
  await expect(firstPageLink).toBeVisible()
  await firstPageLink.click()

  // The full-screen editor HTML is rendered by EditorScreen::render()
  await expect(page.locator('#nivorax-editor-root')).toBeAttached()

  // The React placeholder mounts inside the root node
  await expect(page.locator('#nivorax-editor-placeholder h1')).toContainText('NivoraX Editor')
})
